# Generated by Django 5.1.4 on 2026-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio')),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('duration_seconds', models.FloatField()),
                ('top_genre', models.CharField(max_length=32)),
                ('top_probability', models.FloatField()),
                ('band', models.CharField(max_length=24)),
                ('result', models.JSONField()),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ('-created_at',),
            },
        ),
    ]
